# database
spring:
  profiles:
    active: dev

# server port
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


# jwt key
jwt:
  secret: dlrjsmsbfvmfhwprxmdmlwpdltmsxhzmsdkaghghkzldlqslekdkanehdlrjtdmfdkffurhgkwlaktlqtldh
#  expiration: 3600 # 토큰 만료 시간 (초 단위)